package com.ola.recoverunsold.ui.theme

import androidx.compose.ui.graphics.Color

val themeLightPrimary = Color(0xFF121B9E)
val themeLightOnPrimary = Color(0xFFFFFFFF)
val themeLightSecondary = Color(0xFF08283A)
val themeLightSecondaryVariant = Color(0xFF05141D)
val themeLightOnSecondary = Color(0xFFFFFFFF)
val themeLightError = Color(0xFFBA1A1A)
val themeLightOnError = Color(0xFFFFFFFF)
val themeLightBackground = Color(0xFFFFFBFF)
val themeLightOnBackground = Color(0xFF1B1B1F)
val themeLightSurface = Color(0xFFFFFBFF)
val themeLightOnSurface = Color(0xFF1B1B1F)
val themeLightWarning = Color(0xFFFFB74D)
val themeLightOnWarning = Color(0xFF0C0C0C)
val themeLightSuccess = Color(0xFF81C784)
val themeLightOnSuccess = Color(0xFF0C0C0C)

val themeDarkPrimary = Color(0xFF7278E0)
val themeDarkOnPrimary = Color(0xFFFFFFFF)
val themeDarkSecondary = Color(0xFF08283A)
val themeDarkSecondaryVariant = Color(0xFF05141D)
val themeDarkOnSecondary = Color(0xFFFFFFFF)
val themeDarkError = Color(0xFFFFB4AB)
val themeDarkOnError = Color(0xFF690005)
val themeDarkBackground = Color(0xFF1B1B1F)
val themeDarkOnBackground = Color(0xFFE5E1E6)
val themeDarkSurface = Color(0xFF1B1B1F)
val themeDarkOnSurface = Color(0xFFE5E1E6)
val themeDarkWarning = Color(0xFFF57C00)
val themeDarkOnWarning = Color(0xFF0C0C0C)
val themeDarkSuccess = Color(0xFF388E3C)
val themeDarkOnSuccess = Color(0xFF0C0C0C)
