name: Build the signed apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Put the firebase data in the google-services file
        id: write_google_services
        uses: timheuer/base64-to-file@v1.2.3
        with:
          fileName: 'google-services.json'
          fileDir: '/home/runner/work/RecoverUnsold/RecoverUnsold/app/'
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}
      - name: Insert the google maps api key into the local.properties file
        run: echo ${{ secrets.MAPS_API_KEY }} >> /home/runner/work/RecoverUnsold/RecoverUnsold/local.properties
      - name: Insert the sentry dsn into the local.properties file
        run: echo ${{ secrets.SENTRY_DSN }} >> /home/runner/work/RecoverUnsold/RecoverUnsold/local.properties
      - name: Insert the Kkiapay secret into the local.properties file
        run: echo ${{ secrets.KKIAPAY_API_KEY }} >> /home/runner/work/RecoverUnsold/RecoverUnsold/local.properties
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - uses: actions/upload-artifact@master
        with:
          name: release.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}